astra_db:
  collection_name: "ecommerce_chatbot"

embedding_model:
  provider: "google"
  model: "models/text-embedding-004"

retriever:
  top_k: 3

llm:
  provider: "google"
  model_name: "gemini-1.5-pro"

